# Generated by Django 5.2.14 on 2026-06-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torvu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('highest_level_of_education', models.CharField(max_length=100)),
                ('field_of_study_major', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('most_recent_school_college_university', models.CharField(max_length=255)),
                ('institution_location', models.CharField(max_length=255)),
                ('additional_certifications_qualifications', models.TextField(blank=True)),
                ('employment_status', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=255)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('social_security_number', models.CharField(max_length=20)),
                ('completed_form_w4', models.BooleanField(default=False)),
                ('completed_form_i9', models.BooleanField(default=False)),
                ('professional_summary', models.TextField()),
                ('completed_i9', models.FileField(upload_to='assistance/completed_i9/')),
                ('completed_w4', models.FileField(upload_to='assistance/completed_w4/')),
                ('id_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('issuing_state_authority', models.CharField(max_length=255)),
                ('id_issue_date', models.DateField()),
                ('id_expiration_date', models.DateField()),
                ('front_of_id_document', models.FileField(upload_to='assistance/front_ids/')),
                ('back_of_id_document', models.FileField(upload_to='assistance/back_ids/')),
                ('selfie_holding_id', models.ImageField(upload_to='assistance/selfies/')),
                ('terms_agreement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_employer_job_title', models.CharField(max_length=255)),
                ('previous_employer_name', models.CharField(max_length=255)),
                ('previous_employer_start_date', models.DateField()),
                ('previous_employer_end_date', models.DateField()),
                ('previous_employer_key_responsibilities', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_employments', to='torvu.assistancerequest')),
            ],
        ),
    ]
