# Generated by Django 5.2.14 on 2026-06-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torvu', '0002_assistancerequest_previousemployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerequest',
            name='completed_form_i9',
        ),
        migrations.RemoveField(
            model_name='assistancerequest',
            name='completed_form_w4',
        ),
    ]
