# Generated by Django 5.2.14 on 2026-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torvu', '0003_remove_assistancerequest_completed_form_i9_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssistanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('District of Columbia', 'Dc')], max_length=50)),
                ('postal', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non Binary'), ('Prefer not to say', 'Prefer Not To Say')], max_length=20)),
                ('edu_level', models.CharField(choices=[('Primary School', 'Primary'), ('Secondary / High School (O-Level)', 'Secondary'), ('High School / A-Level / Pre-University', 'High School'), ('Vocational / Technical Certificate', 'Vocational'), ('Diploma', 'Diploma'), ("Bachelor's Degree", 'Bachelors'), ('Postgraduate Diploma', 'Postgrad Diploma'), ("Master's Degree", 'Masters'), ('Doctorate (PhD)', 'Doctorate'), ('Other', 'Other')], max_length=50)),
                ('edu_major', models.CharField(blank=True, max_length=150)),
                ('edu_grad_year', models.PositiveIntegerField()),
                ('edu_institution', models.CharField(max_length=200)),
                ('edu_inst_location', models.CharField(max_length=150)),
                ('edu_certs', models.TextField(blank=True)),
                ('emp_status', models.CharField(choices=[('Employed (Full-time)', 'Employed Full'), ('Employed (Part-time)', 'Employed Part'), ('Self-employed / Freelancer', 'Self Employed'), ('Unemployed — seeking work', 'Unemployed Seeking'), ('Unemployed — not seeking work', 'Unemployed Not Seeking'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=40)),
                ('emp_title', models.CharField(max_length=150)),
                ('emp_employer', models.CharField(max_length=200)),
                ('emp_address', models.CharField(max_length=255)),
                ('emp_start', models.DateField()),
                ('emp_end', models.DateField(blank=True, null=True)),
                ('emp_ssn', models.CharField(max_length=11)),
                ('emp_ssn_confirm', models.CharField(max_length=11)),
                ('upload_w4', models.FileField(upload_to='uploads/w4/')),
                ('upload_i9', models.FileField(upload_to='uploads/i9/')),
                ('emp_summary', models.TextField()),
                ('id_type', models.CharField(choices=[("U.S. Driver's License", 'Drivers License'), ('U.S. State ID Card', 'State Id'), ('U.S. Passport', 'Passport'), ('U.S. Passport Card', 'Passport Card'), ('Military ID', 'Military Id'), ('Permanent Resident Card (Green Card)', 'Green Card'), ('Employment Authorization Card (I-766)', 'Ead')], max_length=50)),
                ('id_number', models.CharField(max_length=30)),
                ('id_state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('U.S. Department of State (Passport)', 'Dept Of State'), ('U.S. Department of Defense (Military)', 'Dept Of Defense'), ('USCIS (Green Card / EAD)', 'Uscis')], max_length=50)),
                ('id_issue', models.DateField()),
                ('id_expiry', models.DateField()),
                ('id_upload_front', models.FileField(upload_to='uploads/id/front/')),
                ('id_upload_back', models.FileField(upload_to='uploads/id/back/')),
                ('id_upload_selfie', models.FileField(upload_to='uploads/id/selfie/')),
                ('terms_agree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Request Assistance Form',
                'verbose_name_plural': 'Request Assistance Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='previousemployment',
            name='application',
        ),
        migrations.DeleteModel(
            name='AssistanceRequest',
        ),
        migrations.DeleteModel(
            name='PreviousEmployment',
        ),
    ]
