# Generated by Django 5.2.14 on 2026-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torvu', '0004_requestassistancemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='edu_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='emp_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='id_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='id_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestassistancemodel',
            name='postal',
            field=models.CharField(max_length=20),
        ),
    ]
